on:
  push:
    tags:
    - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout driver
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/driver
      - name: checkout metabase
        uses: actions/checkout@v4
        with:
          repository: metabase/metabase
          path: ${{ github.workspace }}/metabase
      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 'latest'
      - name: Build project
        run: |
          export DRIVER_PATH=${{ github.workspace }}/driver
          cd ${{ github.workspace }}/metabase
          clojure \
            -Sdeps "{:aliases {:greptimedb {:extra-deps {com.metabase/greptimedb-driver {:local/root \"$DRIVER_PATH\"}}}}}"  \
            -X:build:greptimedb \
            build-drivers.build-driver/build-driver! \
            "{:driver :greptimedb, :project-dir \"$DRIVER_PATH\", :target-dir \"$DRIVER_PATH/target\"}"
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/driver/target/greptimedb.metabase-driver.jar
          generate_release_notes: true
          prerelease: false
